---
- name: Deploy applications to servers
  hosts: all
  roles:
    - role: deploy_app
      vars:
        ansible_python_interpreter: /usr/bin/python3
        applications:
          - { name: "backend", image: "ghcr.io/multi-player-arena/hackathon-mpa/back",version: "main", port: 80, application_port: 8080 }
          - { name: "frontend", image: "ghcr.io/multi-player-arena/hackathon-mpa/front", version: "main", port: 82 }